# Generated by Django 4.2.4 on 2023-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttrpg_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
