# Generated by Django 4.2.4 on 2023-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttrpg_store_app', '0004_alter_cart_options_alter_cartproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marked_price',
            field=models.PositiveIntegerField(help_text='Введите цену товара без скидки', null=True, verbose_name='Цена товара без скидки'),
        ),
    ]
