# Generated by Django 4.2.4 on 2023-09-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttrpg_store_app', '0005_alter_product_marked_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Введите название товара', max_length=60, verbose_name='Название товара'),
        ),
    ]
